# Generated by Django 5.2 on 2025-04-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('hkid_prefix', models.CharField(max_length=4)),
                ('date_of_birth', models.DateField()),
                ('unique_identifier', models.CharField(editable=False, max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='DraftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('certificate', 'Certificate'), ('academic_results', 'Academic Results'), ('awards', 'Awards')], max_length=20)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuing_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.student')),
            ],
            options={
                'verbose_name': 'Draft Certificate',
                'verbose_name_plural': 'Draft Certificates',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_hash', models.CharField(max_length=66, unique=True)),
                ('certificate_type', models.CharField(choices=[('certificate', 'Certificate'), ('academic_results', 'Academic Results'), ('awards', 'Awards')], max_length=20)),
                ('signed_hash', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuing_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_certificates', to='certificates.student')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
