# Generated by Django 5.2 on 2025-04-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('education business', 'Education Business'), ('primary school', 'Primary School'), ('secondary school', 'Secondary School'), ('tertiary level', 'Tertiary Level')], max_length=50, unique=True)),
                ('allowed_certificate_types', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unique_identifier', models.CharField(editable=False, max_length=64, unique=True)),
                ('ethereum_address', models.CharField(editable=False, max_length=42, unique=True)),
                ('public_key', models.TextField(blank=True)),
                ('private_key', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to=settings.AUTH_USER_MODEL)),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutiontype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Username / Sub-division')),
                ('password', models.CharField(max_length=128)),
                ('public_key', models.TextField(blank=True)),
                ('private_key', models.TextField(blank=True)),
                ('unique_identifier', models.CharField(editable=False, max_length=100, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='Belong to Institution')),
            ],
            options={
                'verbose_name': 'Institution User',
                'verbose_name_plural': 'Institution Users',
            },
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_institution_user'),
        ),
    ]
