# Generated by Django 5.2 on 2025-04-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='full_name',
            field=models.CharField(default=None, help_text='Full institution name, e.g. The Chinese University of Hong Kong', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the user, e.g. C. F. Ho', max_length=300),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Short name or code, e.g. CUHK', max_length=200),
        ),
    ]
