# Generated by Django 5.2 on 2025-04-19 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_full_name_institutionuser_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='username',
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='institution_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='full_name',
            field=models.CharField(help_text='Full institution name, e.g. The University of Hong Kong', max_length=300),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Short name or code, e.g. HKU', max_length=200),
        ),
    ]
